server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server

management:
  endpoint:
    shutdown:
      enabled: true
  server:
    port: 20012
    address: 127.0.0.1
  endpoints:
    shutdown:
      sensitive: false
    web:
      exposure:
        include: shutdown